name: Build Windows and Mac Apps

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests lxml openpyxl pyinstaller

      - name: Build Windows EXE
        run: |
          pyinstaller --onefile tefas_funds.py

      - name: Upload Windows EXE
        uses: actions/upload-artifact@v4
        with:
          name: tefas_funds_windows_exe
          path: dist/tefas_funds.exe

  build-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests lxml openpyxl pyinstaller

      - name: Build Mac executable
        run: |
          pyinstaller --onefile tefas_funds.py

      - name: Upload Mac executable
        uses: actions/upload-artifact@v4
        with:
          name: tefas_funds_mac
          path: dist/tefas_funds
